spring:
  security:
    user:
      #Этот конфиг создаст пользователя с именем catalogue_service_user, паролем password и ролью SERVICE.
      name: catalogue_service_user
      password: '{noop}password'
      roles: SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogue
    username: lokrip
    password: lol1234lol1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    schemas:
      - public
      - catalogue
server:
  port: 8081

logging:
 level:
  sql: info
